"""
config.py — central configuration for CeoWatcher.

Add tickers to COMPANIES to expand coverage; everything else auto-adapts.
Set EDGAR_IDENTITY via the EDGAR_IDENTITY environment variable on Render,
or drop it in a local .env file (loaded automatically by python-dotenv).
"""

import os
from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# Identity (required by SEC for edgartools API access)
# ---------------------------------------------------------------------------
EDGAR_IDENTITY: str = os.environ.get("EDGAR_IDENTITY", "r63848@proton.me")

# ---------------------------------------------------------------------------
# Company watchlist  — add rows here to expand coverage
# ---------------------------------------------------------------------------
# Full S&P 500 constituent list (503 stocks, Feb 2025).
# BRK.B / BF.B use hyphens for yfinance compatibility.
# MRSH corrected to MMC (Marsh & McLennan).
COMPANIES: list[tuple[str, str]] = [
    ("MMM",   "3M Company"),
    ("AOS",   "A. O. Smith Corporation"),
    ("ABT",   "Abbott Laboratories"),
    ("ABBV",  "AbbVie Inc."),
    ("ACN",   "Accenture plc"),
    ("ADBE",  "Adobe Inc."),
    ("AMD",   "Advanced Micro Devices"),
    ("AES",   "AES Corporation"),
    ("AFL",   "Aflac Incorporated"),
    ("A",     "Agilent Technologies"),
    ("APD",   "Air Products and Chemicals"),
    ("ABNB",  "Airbnb Inc."),
    ("AKAM",  "Akamai Technologies"),
    ("ALB",   "Albemarle Corporation"),
    ("ARE",   "Alexandria Real Estate Equities"),
    ("ALGN",  "Align Technology"),
    ("ALLE",  "Allegion plc"),
    ("LNT",   "Alliant Energy Corporation"),
    ("ALL",   "Allstate Corporation"),
    ("GOOGL", "Alphabet Inc. Class A"),
    ("GOOG",  "Alphabet Inc. Class C"),
    ("MO",    "Altria Group"),
    ("AMZN",  "Amazon.com Inc."),
    ("AMCR",  "Amcor plc"),
    ("AEE",   "Ameren Corporation"),
    ("AAL",   "American Airlines Group"),
    ("AEP",   "American Electric Power"),
    ("AXP",   "American Express Company"),
    ("AIG",   "American International Group"),
    ("AMT",   "American Tower Corporation"),
    ("AWK",   "American Water Works"),
    ("AMP",   "Ameriprise Financial"),
    ("AME",   "AMETEK Inc."),
    ("AMGN",  "Amgen Inc."),
    ("APH",   "Amphenol Corporation"),
    ("ADI",   "Analog Devices Inc."),
    ("ANSS",  "ANSYS Inc."),
    ("AON",   "Aon plc"),
    ("APA",   "APA Corporation"),
    ("AAPL",  "Apple Inc."),
    ("AMAT",  "Applied Materials Inc."),
    ("APTV",  "Aptiv PLC"),
    ("ACGL",  "Arch Capital Group"),
    ("ADM",   "Archer-Daniels-Midland"),
    ("ANET",  "Arista Networks"),
    ("AJG",   "Arthur J. Gallagher & Co."),
    ("AIZ",   "Assurant Inc."),
    ("T",     "AT&T Inc."),
    ("ATO",   "Atmos Energy Corporation"),
    ("ADSK",  "Autodesk Inc."),
    ("ADP",   "Automatic Data Processing"),
    ("AZO",   "AutoZone Inc."),
    ("AVB",   "AvalonBay Communities"),
    ("AVY",   "Avery Dennison Corporation"),
    ("AXON",  "Axon Enterprise Inc."),
    ("BKR",   "Baker Hughes Company"),
    ("BALL",  "Ball Corporation"),
    ("BAC",   "Bank of America Corporation"),
    ("BAX",   "Baxter International Inc."),
    ("BDX",   "Becton, Dickinson and Company"),
    ("BRK-B", "Berkshire Hathaway Inc."),
    ("BBY",   "Best Buy Co. Inc."),
    ("TECH",  "Bio-Techne Corporation"),
    ("BIIB",  "Biogen Inc."),
    ("BLK",   "BlackRock Inc."),
    ("BX",    "Blackstone Inc."),
    ("BA",    "Boeing Company"),
    ("BKNG",  "Booking Holdings Inc."),
    ("BSX",   "Boston Scientific Corporation"),
    ("BR",    "Broadridge Financial Solutions"),
    ("BRO",   "Brown & Brown Inc."),
    ("BF-B",  "Brown-Forman Corporation"),
    ("BLDR",  "Builders FirstSource Inc."),
    ("BG",    "Bunge Global SA"),
    ("AVGO",  "Broadcom Inc."),
    ("BXP",   "BXP Inc."),
    ("CHRW",  "C.H. Robinson Worldwide"),
    ("CDNS",  "Cadence Design Systems"),
    ("CZR",   "Caesars Entertainment"),
    ("CPT",   "Camden Property Trust"),
    ("CPB",   "Campbell's Company"),
    ("COF",   "Capital One Financial"),
    ("CAH",   "Cardinal Health Inc."),
    ("KMX",   "CarMax Inc."),
    ("CCL",   "Carnival Corporation & plc"),
    ("CARR",  "Carrier Global Corporation"),
    ("CVNA",  "Carvana Co."),
    ("CAT",   "Caterpillar Inc."),
    ("CBOE",  "Cboe Global Markets"),
    ("CBRE",  "CBRE Group Inc."),
    ("CDW",   "CDW Corporation"),
    ("CE",    "Celanese Corporation"),
    ("CNC",   "Centene Corporation"),
    ("CNP",   "CenterPoint Energy"),
    ("CF",    "CF Industries Holdings"),
    ("CRL",   "Charles River Laboratories"),
    ("SCHW",  "Charles Schwab Corporation"),
    ("CHTR",  "Charter Communications"),
    ("CVX",   "Chevron Corporation"),
    ("CMG",   "Chipotle Mexican Grill"),
    ("CB",    "Chubb Limited"),
    ("CHD",   "Church & Dwight Co."),
    ("CI",    "Cigna Group"),
    ("CINF",  "Cincinnati Financial"),
    ("CTAS",  "Cintas Corporation"),
    ("CSCO",  "Cisco Systems Inc."),
    ("C",     "Citigroup Inc."),
    ("CFG",   "Citizens Financial Group"),
    ("CLX",   "Clorox Company"),
    ("CME",   "CME Group Inc."),
    ("CMS",   "CMS Energy Corporation"),
    ("KO",    "Coca-Cola Company"),
    ("COIN",  "Coinbase Global Inc."),
    ("CL",    "Colgate-Palmolive Company"),
    ("CMCSA", "Comcast Corporation"),
    ("CAG",   "Conagra Brands Inc."),
    ("COP",   "ConocoPhillips"),
    ("ED",    "Consolidated Edison"),
    ("CEG",   "Constellation Energy"),
    ("STZ",   "Constellation Brands Inc."),
    ("COO",   "Cooper Companies"),
    ("CPRT",  "Copart Inc."),
    ("GLW",   "Corning Incorporated"),
    ("CPAY",  "Corpay Inc."),
    ("CSGP",  "CoStar Group Inc."),
    ("COST",  "Costco Wholesale Corporation"),
    ("CTRA",  "Coterra Energy Inc."),
    ("CCI",   "Crown Castle Inc."),
    ("CRWD",  "CrowdStrike Holdings"),
    ("CSX",   "CSX Corporation"),
    ("CMI",   "Cummins Inc."),
    ("CVS",   "CVS Health Corporation"),
    ("DHR",   "Danaher Corporation"),
    ("DRI",   "Darden Restaurants Inc."),
    ("DASH",  "DoorDash Inc."),
    ("DVA",   "DaVita Inc."),
    ("DAL",   "Delta Air Lines Inc."),
    ("DD",    "DuPont de Nemours Inc."),
    ("DDOG",  "Datadog Inc."),
    ("DE",    "Deere & Company"),
    ("DELL",  "Dell Technologies Inc."),
    ("DECK",  "Deckers Outdoor Corporation"),
    ("DFS",   "Discover Financial Services"),
    ("DGX",   "Quest Diagnostics"),
    ("DLR",   "Digital Realty Trust"),
    ("DIS",   "Walt Disney Company"),
    ("DG",    "Dollar General Corporation"),
    ("DLTR",  "Dollar Tree Inc."),
    ("D",     "Dominion Energy Inc."),
    ("DOV",   "Dover Corporation"),
    ("DOW",   "Dow Inc."),
    ("DHI",   "D.R. Horton Inc."),
    ("DTE",   "DTE Energy Company"),
    ("DUK",   "Duke Energy Corporation"),
    ("DVN",   "Devon Energy Corporation"),
    ("DXCM",  "DexCom Inc."),
    ("EA",    "Electronic Arts Inc."),
    ("EBAY",  "eBay Inc."),
    ("ECL",   "Ecolab Inc."),
    ("EIX",   "Edison International"),
    ("EW",    "Edwards Lifesciences"),
    ("EMN",   "Eastman Chemical Company"),
    ("ETN",   "Eaton Corporation plc"),
    ("EFX",   "Equifax Inc."),
    ("EQIX",  "Equinix Inc."),
    ("EQR",   "Equity Residential"),
    ("EQT",   "EQT Corporation"),
    ("ESS",   "Essex Property Trust"),
    ("EL",    "Estée Lauder Companies"),
    ("ETSY",  "Etsy Inc."),
    ("EVR",   "Evercore Inc."),
    ("EG",    "Everest Group Ltd."),
    ("EVRG",  "Evergy Inc."),
    ("ES",    "Eversource Energy"),
    ("EXC",   "Exelon Corporation"),
    ("EXPE",  "Expedia Group Inc."),
    ("EXPD",  "Expeditors International"),
    ("EXE",   "Expand Energy Corporation"),
    ("EXR",   "Extra Space Storage"),
    ("XOM",   "Exxon Mobil Corporation"),
    ("FFIV",  "F5 Inc."),
    ("FDS",   "FactSet Research Systems"),
    ("FICO",  "Fair Isaac Corporation"),
    ("FAST",  "Fastenal Company"),
    ("FRT",   "Federal Realty Investment Trust"),
    ("FDX",   "FedEx Corporation"),
    ("FIS",   "Fidelity National Information Services"),
    ("FITB",  "Fifth Third Bancorp"),
    ("FSLR",  "First Solar Inc."),
    ("FE",    "FirstEnergy Corp."),
    ("FI",    "Fiserv Inc."),
    ("F",     "Ford Motor Company"),
    ("FTNT",  "Fortinet Inc."),
    ("FTV",   "Fortive Corporation"),
    ("FOXA",  "Fox Corporation Class A"),
    ("FOX",   "Fox Corporation Class B"),
    ("FCX",   "Freeport-McMoRan Inc."),
    ("GRMN",  "Garmin Ltd."),
    ("IT",    "Gartner Inc."),
    ("GEV",   "GE Vernova Inc."),
    ("GEHC",  "GE HealthCare Technologies"),
    ("GE",    "GE Aerospace"),
    ("GD",    "General Dynamics Corporation"),
    ("GIS",   "General Mills Inc."),
    ("GM",    "General Motors Company"),
    ("GEN",   "Gen Digital Inc."),
    ("GNRC",  "Generac Holdings Inc."),
    ("GPC",   "Genuine Parts Company"),
    ("GILD",  "Gilead Sciences Inc."),
    ("GL",    "Globe Life Inc."),
    ("GPN",   "Global Payments Inc."),
    ("GS",    "Goldman Sachs Group"),
    ("HAL",   "Halliburton Company"),
    ("HIG",   "Hartford Financial Services"),
    ("HAS",   "Hasbro Inc."),
    ("HCA",   "HCA Healthcare Inc."),
    ("DOC",   "Healthpeak Properties"),
    ("HSIC",  "Henry Schein Inc."),
    ("HSY",   "Hershey Company"),
    ("HES",   "Hess Corporation"),
    ("HPE",   "Hewlett Packard Enterprise"),
    ("HLT",   "Hilton Worldwide Holdings"),
    ("HOLX",  "Hologic Inc."),
    ("HD",    "Home Depot Inc."),
    ("HON",   "Honeywell International"),
    ("HRL",   "Hormel Foods Corporation"),
    ("HST",   "Host Hotels & Resorts"),
    ("HWM",   "Howmet Aerospace Inc."),
    ("HPQ",   "HP Inc."),
    ("HUBB",  "Hubbell Incorporated"),
    ("HUM",   "Humana Inc."),
    ("HBAN",  "Huntington Bancshares"),
    ("HII",   "Huntington Ingalls Industries"),
    ("IBM",   "International Business Machines"),
    ("IEX",   "IDEX Corporation"),
    ("IDXX",  "IDEXX Laboratories"),
    ("ITW",   "Illinois Tool Works"),
    ("INCY",  "Incyte Corporation"),
    ("IR",    "Ingersoll Rand Inc."),
    ("PODD",  "Insulet Corporation"),
    ("INTC",  "Intel Corporation"),
    ("ICE",   "Intercontinental Exchange"),
    ("IFF",   "International Flavors & Fragrances"),
    ("IP",    "International Paper Company"),
    ("INTU",  "Intuit Inc."),
    ("INVH",  "Invitation Homes Inc."),
    ("IVZ",   "Invesco Ltd."),
    ("ISRG",  "Intuitive Surgical Inc."),
    ("IQV",   "IQVIA Holdings Inc."),
    ("IRM",   "Iron Mountain Inc."),
    ("IBKR",  "Interactive Brokers Group"),
    ("JBL",   "Jabil Inc."),
    ("JBHT",  "J.B. Hunt Transport Services"),
    ("J",     "Jacobs Solutions Inc."),
    ("JKHY",  "Jack Henry & Associates"),
    ("JNJ",   "Johnson & Johnson"),
    ("JCI",   "Johnson Controls International"),
    ("JPM",   "JPMorgan Chase & Co."),
    ("JNPR",  "Juniper Networks"),
    ("K",     "Kellanova"),
    ("KEY",   "KeyCorp"),
    ("KEYS",  "Keysight Technologies"),
    ("KMB",   "Kimberly-Clark Corporation"),
    ("KIM",   "Kimco Realty Corporation"),
    ("KMI",   "Kinder Morgan Inc."),
    ("KKR",   "KKR & Co. Inc."),
    ("KLAC",  "KLA Corporation"),
    ("KHC",   "Kraft Heinz Company"),
    ("KR",    "Kroger Co."),
    ("LHX",   "L3Harris Technologies"),
    ("LH",    "Labcorp Holdings Inc."),
    ("LRCX",  "Lam Research Corporation"),
    ("LW",    "Lamb Weston Holdings"),
    ("LVS",   "Las Vegas Sands Corp."),
    ("LDOS",  "Leidos Holdings Inc."),
    ("LEN",   "Lennar Corporation"),
    ("LII",   "Lennox International"),
    ("LLY",   "Eli Lilly and Company"),
    ("LIN",   "Linde plc"),
    ("LYV",   "Live Nation Entertainment"),
    ("LKQ",   "LKQ Corporation"),
    ("LMT",   "Lockheed Martin Corporation"),
    ("L",     "Loews Corporation"),
    ("LOW",   "Lowe's Companies Inc."),
    ("LULU",  "lululemon athletica inc."),
    ("LYB",   "LyondellBasell Industries"),
    ("MTB",   "M&T Bank Corporation"),
    ("MRO",   "Marathon Oil Corporation"),
    ("MPC",   "Marathon Petroleum Corporation"),
    ("MAR",   "Marriott International"),
    ("MAS",   "Masco Corporation"),
    ("MA",    "Mastercard Incorporated"),
    ("MTCH",  "Match Group Inc."),
    ("MKC",   "McCormick & Company"),
    ("MCD",   "McDonald's Corporation"),
    ("MCK",   "McKesson Corporation"),
    ("MDT",   "Medtronic plc"),
    ("MRK",   "Merck & Co. Inc."),
    ("META",  "Meta Platforms Inc."),
    ("MET",   "MetLife Inc."),
    ("MTD",   "Mettler-Toledo International"),
    ("MGM",   "MGM Resorts International"),
    ("MCHP",  "Microchip Technology"),
    ("MU",    "Micron Technology Inc."),
    ("MSFT",  "Microsoft Corporation"),
    ("MAA",   "Mid-America Apartment Communities"),
    ("MRNA",  "Moderna Inc."),
    ("MHK",   "Mohawk Industries"),
    ("MOH",   "Molina Healthcare Inc."),
    ("TAP",   "Molson Coors Beverage"),
    ("MDLZ",  "Mondelez International"),
    ("MPWR",  "Monolithic Power Systems"),
    ("MNST",  "Monster Beverage Corporation"),
    ("MCO",   "Moody's Corporation"),
    ("MS",    "Morgan Stanley"),
    ("MOS",   "Mosaic Company"),
    ("MSI",   "Motorola Solutions Inc."),
    ("MSCI",  "MSCI Inc."),
    ("NDAQ",  "Nasdaq Inc."),
    ("NTAP",  "NetApp Inc."),
    ("NFLX",  "Netflix Inc."),
    ("NEM",   "Newmont Corporation"),
    ("NWSA",  "News Corporation Class A"),
    ("NWS",   "News Corporation Class B"),
    ("NEE",   "NextEra Energy Inc."),
    ("NKE",   "NIKE Inc."),
    ("NI",    "NiSource Inc."),
    ("NDSN",  "Nordson Corporation"),
    ("NOC",   "Northrop Grumman Corporation"),
    ("NCLH",  "Norwegian Cruise Line Holdings"),
    ("NRG",   "NRG Energy Inc."),
    ("NUE",   "Nucor Corporation"),
    ("NVDA",  "NVIDIA Corporation"),
    ("NVR",   "NVR Inc."),
    ("NXPI",  "NXP Semiconductors"),
    ("ODFL",  "Old Dominion Freight Line"),
    ("OKE",   "ONEOK Inc."),
    ("ORCL",  "Oracle Corporation"),
    ("OTIS",  "Otis Worldwide Corporation"),
    ("ON",    "ON Semiconductor"),
    ("OXY",   "Occidental Petroleum"),
    ("PCAR",  "PACCAR Inc."),
    ("PKG",   "Packaging Corporation of America"),
    ("PANW",  "Palo Alto Networks Inc."),
    ("PARA",  "Paramount Global"),
    ("PH",    "Parker-Hannifin Corporation"),
    ("PAYX",  "Paychex Inc."),
    ("PAYC",  "Paycom Software Inc."),
    ("PYPL",  "PayPal Holdings Inc."),
    ("PNR",   "Pentair plc"),
    ("PEP",   "PepsiCo Inc."),
    ("PFE",   "Pfizer Inc."),
    ("PCG",   "PG&E Corporation"),
    ("PM",    "Philip Morris International"),
    ("PSX",   "Phillips 66"),
    ("PNW",   "Pinnacle West Capital"),
    ("PLTR",  "Palantir Technologies"),
    ("PLD",   "Prologis Inc."),
    ("PNC",   "PNC Financial Services Group"),
    ("POOL",  "Pool Corporation"),
    ("PPG",   "PPG Industries Inc."),
    ("PPL",   "PPL Corporation"),
    ("PFG",   "Principal Financial Group"),
    ("PG",    "Procter & Gamble Company"),
    ("PGR",   "Progressive Corporation"),
    ("PRU",   "Prudential Financial Inc."),
    ("PTC",   "PTC Inc."),
    ("PSA",   "Public Storage"),
    ("PEG",   "Public Service Enterprise Group"),
    ("PWR",   "Quanta Services Inc."),
    ("QCOM",  "QUALCOMM Incorporated"),
    ("QRVO",  "Qorvo Inc."),
    ("RL",    "Ralph Lauren Corporation"),
    ("RJF",   "Raymond James Financial"),
    ("RTX",   "RTX Corporation"),
    ("O",     "Realty Income Corporation"),
    ("REG",   "Regency Centers Corporation"),
    ("REGN",  "Regeneron Pharmaceuticals"),
    ("RF",    "Regions Financial Corporation"),
    ("RMD",   "ResMed Inc."),
    ("RSG",   "Republic Services Inc."),
    ("RHI",   "Robert Half Inc."),
    ("HOOD",  "Robinhood Markets Inc."),
    ("ROK",   "Rockwell Automation Inc."),
    ("ROL",   "Rollins Inc."),
    ("ROP",   "Roper Technologies Inc."),
    ("ROST",  "Ross Stores Inc."),
    ("RCL",   "Royal Caribbean Cruises"),
    ("SPGI",  "S&P Global Inc."),
    ("SBAC",  "SBA Communications"),
    ("SLB",   "SLB N.V."),
    ("STX",   "Seagate Technology Holdings"),
    ("SRE",   "Sempra"),
    ("NOW",   "ServiceNow Inc."),
    ("SHW",   "Sherwin-Williams Company"),
    ("SNA",   "Snap-on Incorporated"),
    ("SOLV",  "Solventum Corporation"),
    ("SO",    "Southern Company"),
    ("LUV",   "Southwest Airlines Co."),
    ("SPG",   "Simon Property Group"),
    ("SWKS",  "Skyworks Solutions"),
    ("SJM",   "J. M. Smucker Company"),
    ("STE",   "STERIS plc"),
    ("STLD",  "Steel Dynamics Inc."),
    ("STT",   "State Street Corporation"),
    ("SMCI",  "Super Micro Computer"),
    ("SW",    "Smurfit Westrock Plc"),
    ("SYK",   "Stryker Corporation"),
    ("SBUX",  "Starbucks Corporation"),
    ("SYF",   "Synchrony Financial"),
    ("SNPS",  "Synopsys Inc."),
    ("SYY",   "Sysco Corporation"),
    ("TMUS",  "T-Mobile US Inc."),
    ("TRGP",  "Targa Resources Corp."),
    ("TGT",   "Target Corporation"),
    ("TEL",   "TE Connectivity plc"),
    ("TDY",   "Teledyne Technologies"),
    ("TER",   "Teradyne Inc."),
    ("TSLA",  "Tesla Inc."),
    ("TMO",   "Thermo Fisher Scientific"),
    ("TJX",   "TJX Companies Inc."),
    ("TTWO",  "Take-Two Interactive Software"),
    ("TKO",   "TKO Group Holdings"),
    ("TPL",   "Texas Pacific Land"),
    ("TPR",   "Tapestry Inc."),
    ("TXN",   "Texas Instruments"),
    ("TXT",   "Textron Inc."),
    ("TFC",   "Truist Financial Corporation"),
    ("TDG",   "TransDigm Group"),
    ("TT",    "Trane Technologies plc"),
    ("TRV",   "Travelers Companies Inc."),
    ("TRMB",  "Trimble Inc."),
    ("TSCO",  "Tractor Supply Company"),
    ("TROW",  "T. Rowe Price Group"),
    ("TTD",   "Trade Desk Inc."),
    ("TYL",   "Tyler Technologies"),
    ("TSN",   "Tyson Foods Inc."),
    ("UBER",  "Uber Technologies Inc."),
    ("UDR",   "UDR Inc."),
    ("ULTA",  "Ulta Beauty Inc."),
    ("UNH",   "UnitedHealth Group"),
    ("UAL",   "United Airlines Holdings"),
    ("UNP",   "Union Pacific Corporation"),
    ("UPS",   "United Parcel Service"),
    ("URI",   "United Rentals Inc."),
    ("USB",   "U.S. Bancorp"),
    ("V",     "Visa Inc."),
    ("VLO",   "Valero Energy Corporation"),
    ("VTR",   "Ventas Inc."),
    ("VLTO",  "Veralto Corporation"),
    ("VRSN",  "VeriSign Inc."),
    ("VRSK",  "Verisk Analytics"),
    ("VZ",    "Verizon Communications"),
    ("VRTX",  "Vertex Pharmaceuticals"),
    ("VICI",  "VICI Properties Inc."),
    ("VST",   "Vistra Corp."),
    ("VMC",   "Vulcan Materials Company"),
    ("WAB",   "Westinghouse Air Brake Technologies"),
    ("WMT",   "Walmart Inc."),
    ("WBD",   "Warner Bros. Discovery"),
    ("WAT",   "Waters Corporation"),
    ("WEC",   "WEC Energy Group"),
    ("WDC",   "Western Digital Corporation"),
    ("WRB",   "W. R. Berkley Corporation"),
    ("WM",    "Waste Management Inc."),
    ("WFC",   "Wells Fargo & Company"),
    ("WELL",  "Welltower Inc."),
    ("WST",   "West Pharmaceutical Services"),
    ("WY",    "Weyerhaeuser Company"),
    ("WMB",   "Williams Companies Inc."),
    ("WSM",   "Williams-Sonoma Inc."),
    ("WTW",   "Willis Towers Watson"),
    ("WDAY",  "Workday Inc."),
    ("WYNN",  "Wynn Resorts Limited"),
    ("XEL",   "Xcel Energy Inc."),
    ("XYZ",   "Block Inc."),
    ("XYL",   "Xylem Inc."),
    ("YUM",   "Yum! Brands Inc."),
    ("ZBRA",  "Zebra Technologies"),
    ("ZBH",   "Zimmer Biomet Holdings"),
    ("ZTS",   "Zoetis Inc."),
    ("APP",   "AppLovin Corporation"),
    ("ARES",  "Ares Management Corporation"),
    ("CRH",   "CRH plc"),
    ("EME",   "EMCOR Group Inc."),
    ("SNDK",  "Sandisk Corporation"),
    ("KDP",   "Keurig Dr Pepper Inc."),
    ("KVUE",  "Kenvue Inc."),
    ("MLM",   "Martin Marietta Materials"),
    ("RVTY",  "Revvity Inc."),
    ("CIEN",  "Ciena Corporation"),
    ("FANG",  "Diamondback Energy"),
    ("GDDY",  "GoDaddy Inc."),
    ("EPAM",  "EPAM Systems Inc."),
]

# ---------------------------------------------------------------------------
# Historical backfill
# ---------------------------------------------------------------------------
BACKFILL_START: str = "2015-01-01"   # 10 years of Form 4 history

# ---------------------------------------------------------------------------
# Return-window definitions  (label → days)
# Used in analytics pre-computation and dashboard filters
# ---------------------------------------------------------------------------
RETURN_WINDOWS: dict[str, int] = {
    "2w":  14,
    "1m":  30,
    "3m":  90,
    "6m":  180,
    "1y":  365,
    "2y":  730,
    "3y":  1095,
}

# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------
# Render injects DATABASE_URL automatically.
# For local dev: set it in .env as DATABASE_URL=postgresql://user:pass@host/db
DATABASE_URL: str = os.environ.get(
    "DATABASE_URL",
    "postgresql://ceowatcher:ceowatcher@localhost:5432/ceowatcher",
)
# SQLAlchemy requires postgresql:// not postgres://
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

# Neon requires SSL — append if not already present
if "neon.tech" in DATABASE_URL and "sslmode" not in DATABASE_URL:
    DATABASE_URL += "?sslmode=require"
